// Embeds the bundled typefaces as @font-face rules carrying data URIs, so a
// rendered document draws in its own letterforms while still making zero
// external requests. The generated document stylesheet carries shared faces;
// Mermaid-specific faces are emitted separately for conditional packaging.

import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = fileURLToPath(new URL("..", import.meta.url));
const fontsDir = join(repoRoot, "assets", "fonts");
const stylesheetPath = join(repoRoot, "src", "render", "fonts.generated.css");
const mermaidModulePath = join(
  repoRoot,
  "src",
  "components",
  "mermaid-diagram",
  "font.generated.ts",
);

// Each entry is one authored face. `sizeAdjust` normalizes a typeface whose
// x-height differs from the reading font, so swapping families does not change
// how large the copy reads. assets/fonts/README.md owns the licensing record.
const FACES = [
  {
    family: "Patrick Hand",
    file: "patrick-hand-400.woff2",
    weight: 400,
    style: "normal",
    sizeAdjust: "108%",
    mermaid: false,
    unicodeRange: null,
    mermaidSample: null,
  },
  {
    family: "Noto Sans",
    file: "noto-sans-latin-400-normal.woff2",
    weight: 400,
    style: "normal",
    sizeAdjust: null,
    mermaid: true,
    unicodeRange: null,
    mermaidSample: "Aa",
  },
  {
    family: "Noto Sans",
    file: "noto-sans-latin-600-normal.woff2",
    weight: 600,
    style: "normal",
    sizeAdjust: null,
    mermaid: true,
    unicodeRange: null,
    mermaidSample: "Aa",
  },
  {
    family: "Noto Sans",
    file: "noto-sans-latin-700-normal.woff2",
    weight: 700,
    style: "normal",
    sizeAdjust: null,
    mermaid: true,
    unicodeRange: null,
    mermaidSample: "Aa",
  },
  ...[400, 600, 700].flatMap((weight) => [
    {
      family: "Noto Sans SC",
      file: `noto-sans-sc-118-${weight}-normal.woff2`,
      weight,
      style: "normal",
      sizeAdjust: null,
      mermaid: true,
      unicodeRange: "U+5F00",
      mermaidSample: "开",
    },
    {
      family: "Noto Sans SC",
      file: `noto-sans-sc-116-${weight}-normal.woff2`,
      weight,
      style: "normal",
      sizeAdjust: null,
      mermaid: true,
      unicodeRange: "U+59CB",
      mermaidSample: "始",
    },
    {
      family: "Noto Sans SC",
      file: `noto-sans-sc-87-${weight}-normal.woff2`,
      weight,
      style: "normal",
      sizeAdjust: null,
      mermaid: true,
      unicodeRange: "U+2705",
      mermaidSample: "✅",
    },
  ]),
];

const face = ({ family, file, weight, style, sizeAdjust, unicodeRange }) => {
  const encoded = readFileSync(join(fontsDir, file)).toString("base64");
  return `@font-face {
  font-family: "${family}";
  font-style: ${style};
  font-weight: ${weight};
  font-display: block;
${sizeAdjust === null ? "" : `  size-adjust: ${sizeAdjust};\n`}${unicodeRange === null ? "" : `  unicode-range: ${unicodeRange};\n`}  src: url(data:font/woff2;base64,${encoded}) format("woff2");
}`;
};

writeFileSync(
  stylesheetPath,
  `/* CSS escape hatch: this generated token definition embeds shared bundled typefaces.\nGenerated by scripts/gen-fonts.mjs from assets/fonts/. Do not edit. */\n\n${FACES.filter(
    ({ mermaid }) => !mermaid,
  )
    .map(face)
    .join("\n\n")}\n`,
  "utf8",
);
const mermaidFaces = FACES.filter(({ mermaid }) => mermaid);
const mermaidCss = mermaidFaces.map(face).join("\n\n");
const mermaidFamilies = [...new Set(mermaidFaces.map(({ family }) => family))];
const probeText = new Map();
for (const { family, weight, mermaidSample } of mermaidFaces) {
  const key = `${family}\u0000${weight}`;
  const current = probeText.get(key) ?? "";
  probeText.set(key, [...new Set([...current, ...mermaidSample])].join(""));
}
const mermaidProbes = [...probeText].map(([key, text]) => {
  const [family, weight] = key.split("\u0000");
  return { family, weight: Number(weight), text };
});
writeFileSync(
  mermaidModulePath,
  `// Generated by scripts/gen-fonts.mjs from assets/fonts/. Do not edit.\n\nexport const MERMAID_FONT_FAMILY = ${JSON.stringify(mermaidFamilies.join(", "))};\nexport const MERMAID_FONT_PROBES = ${JSON.stringify(mermaidProbes)} as const;\nexport const MERMAID_FONT_CSS = ${JSON.stringify(mermaidCss)};\n`,
  "utf8",
);
console.log(
  `generated ${stylesheetPath} and ${mermaidModulePath} (${FACES.length} faces)`,
);
