// Embeds pre-processed branding PNGs as generated TypeScript constants, so
// rendered documents can include logos and favicons without runtime file reads
// or external requests.

import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = fileURLToPath(new URL("..", import.meta.url));
const assetsDir = join(repoRoot, "assets");
const outputPath = join(repoRoot, "src", "render", "branding.generated.ts");

const readPngDataUri = (fileName) => {
  const encoded = readFileSync(join(assetsDir, fileName)).toString("base64");
  return `data:image/png;base64,${encoded}`;
};

const assets = [
  ["LOGO_LIGHT_SRC", "logo-light.png"],
  ["LOGO_DARK_SRC", "logo-dark.png"],
  ["FAVICON_16_SRC", "favicon-16.png"],
  ["FAVICON_32_SRC", "favicon-32.png"],
];

const exports = assets
  .map(
    ([exportName, fileName]) =>
      `export const ${exportName} = ${JSON.stringify(readPngDataUri(fileName))};`,
  )
  .join("\n");

writeFileSync(
  outputPath,
  `// Generated by scripts/gen-assets.mjs from assets/*.png. Do not edit.\n\n${exports}\n`,
  "utf8",
);
console.log(`generated ${outputPath} (${assets.length} assets)`);
