// Embeds the branding assets as generated TypeScript constants, so rendered
// documents can include logos and favicons without runtime file reads or
// external requests.

import { readFileSync, writeFileSync } from "node:fs";
import { extname, join } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = fileURLToPath(new URL("..", import.meta.url));
const assetsDir = join(repoRoot, "assets");
const outputPath = join(repoRoot, "src", "render", "branding.generated.ts");

const MIME_TYPES = {
  ".ico": "image/x-icon",
  ".png": "image/png",
  ".svg": "image/svg+xml",
};

// Reads a checked-in branding asset into the data URI form used by the renderer.
const readDataUri = (fileName) => {
  const mime = MIME_TYPES[extname(fileName)];
  if (mime === undefined) {
    throw new Error(`gen-assets: no mime type mapped for ${fileName}`);
  }
  const encoded = readFileSync(join(assetsDir, fileName)).toString("base64");
  return `data:${mime};base64,${encoded}`;
};

const assets = [
  ["LOGO_LIGHT_SRC", "logo-light.svg"],
  ["LOGO_DARK_SRC", "logo-dark.svg"],
  ["FAVICON_LIGHT_SRC", "favicon-light.ico"],
  ["FAVICON_DARK_SRC", "favicon-dark.ico"],
];

const exports = assets
  .map(
    ([exportName, fileName]) =>
      `export const ${exportName} = ${JSON.stringify(readDataUri(fileName))};`,
  )
  .join("\n");

writeFileSync(
  outputPath,
  `// Generated by scripts/gen-assets.mjs from assets/. Do not edit.\n\n${exports}\n`,
  "utf8",
);
console.log(`generated ${outputPath} (${assets.length} assets)`);
