// Compiles src/render/global.css with the Tailwind CLI and wraps the result in
// a generated TypeScript module, so the renderer can inline the stylesheet
// into documents while staying a pure function with no runtime file reads.

import { execFileSync } from "node:child_process";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = fileURLToPath(new URL("..", import.meta.url));
const inputPath = join(repoRoot, "src", "render", "global.css");
const outputPath = join(repoRoot, "src", "render", "global.generated.ts");
const tailwindBin = join(repoRoot, "node_modules", ".bin", "tailwindcss");

const tempDir = mkdtempSync(join(tmpdir(), "big-plan-css-"));
try {
  const compiledPath = join(tempDir, "global.css");
  execFileSync(tailwindBin, ["-i", inputPath, "-o", compiledPath, "--minify"], {
    cwd: repoRoot,
    stdio: ["ignore", "inherit", "inherit"],
  });
  const css = readFileSync(compiledPath, "utf8").trim();

  // Escape for a template literal so arbitrary CSS survives the round trip.
  const escaped = css
    .replaceAll("\\", "\\\\")
    .replaceAll("`", "\\`")
    .replaceAll("${", "\\${");

  writeFileSync(
    outputPath,
    `// Generated by scripts/gen-css.mjs from global.css. Do not edit.\n\nexport const GLOBAL_CSS = \`${escaped}\`;\n`,
    "utf8",
  );
  console.log(`generated ${outputPath} (${css.length} bytes of CSS)`);
} finally {
  rmSync(tempDir, { recursive: true, force: true });
}
