// Embeds the authored agent skill document as a generated TypeScript constant,
// so `big-plan skill` ships the same text that is version-controlled under
// assets/skill/ without runtime file reads after publish.

import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = fileURLToPath(new URL("..", import.meta.url));
const skillPath = join(repoRoot, "assets", "skill", "SKILL.md");
const outputPath = join(
  repoRoot,
  "src",
  "cli",
  "skill",
  "content.generated.ts",
);

const skill = readFileSync(skillPath, "utf8");

writeFileSync(
  outputPath,
  [
    "// Generated by scripts/gen-skill.mjs from assets/skill/SKILL.md.",
    "// Do not edit.",
    "",
    `export const SKILL_MARKDOWN = ${JSON.stringify(skill)};`,
    "",
  ].join("\n"),
  "utf8",
);
console.log(`generated ${outputPath} (skill ${skill.length} characters)`);
