// Embeds the bundled typefaces as @font-face rules carrying data URIs, so a
// rendered document draws in its own letterforms while still making zero
// external requests. The generated stylesheet is imported by global.css and
// compiled into the same embedded style block as everything else.

import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = fileURLToPath(new URL("..", import.meta.url));
const fontsDir = join(repoRoot, "assets", "fonts");
const outputPath = join(
  repoRoot,
  "src",
  "components",
  "wireframe",
  "font.generated.css",
);

// Each entry is one authored face. `sizeAdjust` normalizes a typeface whose
// x-height differs from the reading font, so swapping families does not change
// how large the copy reads. assets/fonts/README.md owns the licensing record.
const FACES = [
  {
    family: "Patrick Hand",
    file: "patrick-hand-400.woff2",
    weight: 400,
    style: "normal",
    sizeAdjust: "108%",
  },
];

const face = ({ family, file, weight, style, sizeAdjust }) => {
  const encoded = readFileSync(join(fontsDir, file)).toString("base64");
  return `@font-face {
  font-family: "${family}";
  font-style: ${style};
  font-weight: ${weight};
  font-display: block;
  size-adjust: ${sizeAdjust};
  src: url(data:font/woff2;base64,${encoded}) format("woff2");
}`;
};

writeFileSync(
  outputPath,
  `/* CSS escape hatch: generated markup owns the bundled @font-face rule.\n   Generated by scripts/gen-fonts.mjs from assets/fonts/. Do not edit. */\n\n${FACES.map(face).join("\n\n")}\n`,
  "utf8",
);
console.log(
  `generated ${outputPath} (${FACES.length} face${FACES.length === 1 ? "" : "s"})`,
);
